path:
  # Input
  model_dir: /Users/douzhixin/Developer/qPacking/code/checkpoints/80/20250721_degree_esm2-150_80_v1/best
  model_src: finetuned
  #model_dir: /Users/douzhixin/Developer/qPacking/code/checkpoints/esm2_t30_150M_UR50D
  #model_src: official
  pkl_file: /Users/douzhixin/Developer/qPacking/data/benchmark/tim-db/ss.pkl
  fasta_file: /Users/douzhixin/Developer/qPacking/data/benchmark/tim-db/ss.fasta

  # Output
  checkpoints_dir: /Users/douzhixin/Developer/qPacking/code/checkpoints/qpacking
  logging_dir: /Users/douzhixin/Developer/qPacking/code/logs
  tokenized_cache_path: /Users/douzhixin/Developer/qPacking/data/benchmark/tim-db/ss_tokenized_cache

training_args:
  seed: 3407
  lr: 2.0e-5
  num_epochs: 1
  batch_size: 16
  test_ratio: 0.2
  eval_strategy: steps
  logging_strategy: steps
  eval_steps: 100
  save_steps: 100
  save_strategy: steps
  save_total_limit: 3
  logging_steps: 1
  reporter: mlflow
  metric_for_best_model: MSE
  greater_is_better: False
